### ISSUE TITLE
Unsupported / Wrong Network

### ISSUE THREAD

**Issue by borisblock3007** [carrot-kpi/v1-monorepo#113]
Update the 'unsupported network' state
<img width="221" alt="Screenshot 2023-02-14 at 17 20 21" src="https://user-images.githubusercontent.com/25454493/218707281-e2bc3771-0912-4747-b40c-748460b13854.png">

**Comment by luzzif** [comment]
Is this task meant as a design task for you to change how the unsupported state displays?

**Comment by borisblock3007** [comment]
actually this task was for the wrong network modal lol
here is the design 
![Image](https://user-images.githubusercontent.com/25454493/225380477-be5d725f-d5e9-4b32-acfc-9d3e70758457.png)
