### ISSUE TITLE
Tags interactions

### ISSUE THREAD

**Issue by borisblock3007** [carrot-kpi/v1-monorepo#114]
Specify tags interactions flow throughout the dapp

**Comment by borisblock3007** [comment]
It's not clear that you need to press enter to create a tag, added an explanation and ability to separate them by a comma
<img width="385" alt="Screenshot 2023-03-01 at 16 30 42" src="https://user-images.githubusercontent.com/25454493/222099605-3a7bde95-46ee-41bf-9047-e7620282bf6d.png">

**Comment by guerrap** [comment]
Right now the tags input is as follows, I think we can keep it this way for now, @luzzif ?
![image](https://user-images.githubusercontent.com/9011637/222101465-f316130c-7c14-423c-b42b-b84a3088593d.png)

**Comment by luzzif** [comment]
I think that works, closing this.
