### ISSUE TITLE
Simplify Step 1

### ISSUE THREAD

**Issue by borisblock3007** [carrot-kpi/v1-monorepo#115]
Step 1 looks a bit long, we need to make it more compact
<img width="462" alt="Screenshot 2023-02-14 at 17 18 50" src="https://user-images.githubusercontent.com/25454493/218725787-672bc99f-ccc5-4828-9577-cd8b24da2fb4.png">

**Comment by borisblock3007** [comment]
updated it
<img width="434" alt="Screenshot 2023-02-28 at 15 32 01" src="https://user-images.githubusercontent.com/25454493/221797313-d9188c56-8407-4668-af92-4ee736505a45.png">

**Comment by luzzif** [comment]
This has been done in the latest iterations of the creation form
