### ISSUE TITLE
Add connect wallet button to creation form in step 6 in the case the wallet is not connected.

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/v1-monorepo#119]
On step 6 if the wallet is not connected we should ask to connect before asking for approval of token.

We allow people to get to step 6 without wallet connected.  But we should check if they have the wallet connected in this step. If don't we should ask to connect it, so they can approve the token and create the campaign.

A connect wallet button here before showing "approve xxx token", so people know they should connect the wallet before creating campaign.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5664434/219425220-22c655b9-3e8d-450c-9ba0-ff8a86f4a2eb.png">

**Comment by borisblock3007** [comment]
First draft, can we start with a blank page with a 'connect button' message?
<img width="611" alt="Screenshot 2023-02-21 at 22 22 30" src="https://user-images.githubusercontent.com/25454493/220386125-22d30f54-5cf9-4e17-9769-70a561e54e0d.png">

**Comment by luzzif** [comment]
I'm not even sure if creation forms should be accessible at all without a connected wallet. A suggestion: when "use template" is clicked on a template card in order to use it, if the wallet is not connected let's show the user the wallet popover in order to make them connect. No?
