### ISSUE TITLE
When picking collateral, make it clear that fees are present

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/v1-monorepo#122]
When picking collateral we must show the user how much goes to the platform in fees.

**Comment by borisblock3007** [comment]
Added protocol fees below collateral as a first draft option
<img width="418" alt="Screenshot 2023-02-21 at 22 01 27" src="https://user-images.githubusercontent.com/25454493/220380772-9704192f-7706-4cea-a25d-6d240cb89c00.png">

**Comment by luzzif** [comment]
That works! I'd implement it so that if am amount is typed the protocol fee shows both percentage and collateral amount taken.

**Comment by luzzif** [comment]
We should also show both the total amount and amount after fees in the table below though. As of now I implemented it this way, but it doesn't look too great:

![image](https://user-images.githubusercontent.com/12766550/220420085-37bb1974-0a97-4bbf-857d-72254f8d115c.png)

**Comment by guerrap** [comment]
Maybe we could add a tooltip that shows the amount and the amount after the fees, while in the table we only show the amount after the fees.

**Comment by borisblock3007** [comment]
maybe like this? 
<img width="594" alt="Screenshot 2023-02-27 at 17 46 51" src="https://user-images.githubusercontent.com/25454493/221543721-b2fadde7-c645-4977-a854-ae80896a0186.png">

**Comment by guerrap** [comment]
That looks good, I think we can go with this, @luzzif ?

**Comment by luzzif** [comment]
Looking good, I'm about to implement this

**Comment by luzzif** [comment]
Should be implemented in the latest template version
