### ISSUE TITLE
Design what happens once a KPI token is created

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/v1-monorepo#128]
We need a design for what to show to the user once a KPI token is created, after the last step

**Comment by borisblock3007** [comment]
I suggest adding another screen showcasing created campaign card, which can be very simple like this
<img width="321" alt="Screenshot 2023-03-01 at 17 38 39" src="https://user-images.githubusercontent.com/25454493/222115767-4239945e-a50d-4fbe-b681-5a18f4f7a91f.png">

**Comment by luzzif** [comment]
I really like this. I think we can probablyadd this to ready and create the implementation task? as a first version it will probably be without card though, just the simple message + button.
