### ISSUE TITLE
Redesign the last ERC20 KPI token creation form step

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/v1-monorepo#129]
The last step should show a recap of the user configuration and multiple approve buttons based on how many collaterals were picked.

**Comment by borisblock3007** [comment]
I moved the approve button closer to the collaterals. Can we approve multiple collaterals with just 1 button like here?
<img width="618" alt="Screenshot 2023-02-21 at 21 47 25" src="https://user-images.githubusercontent.com/25454493/220377294-d2d33b86-1165-4f3a-bf49-ad3770f874bf.png">

**Comment by luzzif** [comment]
It's possible but I'm not super sure it's immediately clear to users?

**Comment by borisblock3007** [comment]
the information icon should have an explanation for the users :)

**Comment by borisblock3007** [comment]
Maybe this will look more clear?
<img width="723" alt="Screenshot 2023-03-01 at 15 45 45" src="https://user-images.githubusercontent.com/25454493/222088818-38cd74ff-2b3f-4125-af72-125d7a16fd18.png">

**Comment by borisblock3007** [comment]
another option
<img width="674" alt="Screenshot 2023-03-01 at 18 30 09" src="https://user-images.githubusercontent.com/25454493/222127233-95de5cc0-c33e-4d1d-b7d1-db45c4438090.png">

**Comment by luzzif** [comment]
I've implemented the first option.
