### ISSUE TITLE
Design expiration field in ERC20 KPI token creation form 

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/v1-monorepo#130]
An additional param needs to be added to the ERC20 KPI token creation form: expiration. The expiration is a timestamp in the future. If the KPI token isn't finalized by then, it expires and funds are either sent back to the creator of distributed to the users depending on configuration.

**Comment by borisblock3007** [comment]
Is it ok if we add the expiration timestamp on this step?
<img width="499" alt="Screenshot 2023-02-27 at 18 28 38" src="https://user-images.githubusercontent.com/25454493/221552533-b15e4dc2-4f70-4192-aeb9-759467dde8c1.png">

**Comment by luzzif** [comment]
I've just implemented this and I've added it to the general data section (first step). This doesn't have to do with outcome configuration, it's something generic.
