### ISSUE TITLE
Condition of Campaign missing?

### ISSUE THREAD

**Issue by skyminert** [carrot-kpi/v1-monorepo#134]
If you go into a Campaign:
https://carrot-preview.on.fleek.co/#/campaigns/0xb27704A2ED25c602EcE829c66417B7344A9b1788
Where is the condition?

![image](https://user-images.githubusercontent.com/57817726/220410520-73c4f4a5-9f6f-4fe1-9d6a-8b1825d0f96c.png)

Do we have "Title" twice?
"Testers of Carrot" is title

**Comment by guerrap** [comment]
Removed the title inside the card, and fixed the missing description (condition) in the card.
