### ISSUE TITLE
Replace the theme switch with a select

### ISSUE THREAD

**Issue by guerrap** [carrot-kpi/v1-monorepo#139]
The theme switch should be replaced by a select since the user can choose between `light`, `dark`, and `system`.

**Comment by borisblock3007** [comment]
how the system theme will look like? here are some options for the select
<img width="479" alt="Screenshot 2023-02-28 at 16 42 16" src="https://user-images.githubusercontent.com/25454493/221814509-8631577d-9602-4396-8d9c-11cc4881fe5e.png">

**Comment by luzzif** [comment]
As of now I've implemented the second version, which was the quicker to get done
