### ISSUE TITLE
Create Reality.eth iframe design

### ISSUE THREAD

**Issue by borisblock3007** [carrot-kpi/v1-monorepo#149]
It should have a couple of different states.
When the Reality.eth question hasn't opened for answers yet, we just show the question and a countdown.
Once it has opened, we show the answer form instead of the countdown.
The form might consist of a checkbox for yes/no answers, a number input for uint answers, or it can be marked as invalid.
After marking the question as invalid answerers should also have the possibility to call for arbitration.
But Reality.eth v3 also supports a question being marked as "answered too soon", which means the results are not yet known while the question is answerable already. When a question is answered and finalized as "answered too soon", there needs to be a button to reopen it.
![paste (16)](https://user-images.githubusercontent.com/25454493/222120319-cb94b3ac-38d0-4e37-b367-e30c93189654.png)

**Comment by borisblock3007** [comment]
An early version:

![Image](https://user-images.githubusercontent.com/25454493/223625765-bf8e6e93-6de7-4043-a9ef-2d64bd9c4d17.png)

**Comment by guerrap** [comment]
@borisblock3007 we should also display the latest answer (the one with the higher bond) even if it's not yet finalized. This way the user can see the latest answer.

**Comment by borisblock3007** [comment]
does this option looks better?
![Image](https://user-images.githubusercontent.com/25454493/224235647-91ca1b73-13de-4927-8ac7-286ca51e8ab1.png)

**Comment by guerrap** [comment]
I think it works, but I'd also add the bond provided next to the current answer (it should also be visible once the answer is finalized).
