### ISSUE TITLE
Implement KPI campaign search on Subgraph

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/v1-monorepo#153]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5664434/225320297-743ad5a9-cd99-47a4-abb6-232bf24fe149.png">

**Comment by luzzif** [comment]
Ser I think we can reuse this issue right here https://github.com/carrot-kpi/v1-monorepo/issues/24 without opening a new one.

**Comment by Diogomartf** [comment]
I'm thinking of splitting the filtering in smaller tasks. Otherwise is difficult to review and discuss ideas.

**Comment by Diogomartf** [comment]
I think I can create a relationship between issues, I'll try to do that.

**Comment by Diogomartf** [comment]
this issue is related to #24
