### ISSUE TITLE
Template error state

### ISSUE THREAD

**Issue by guerrap** [carrot-kpi/v1-monorepo#204]
There are 4 places where an error can occur while loading a template:

- opening the creation form for a template
- loading the oracle creation form in the oracle configuration step (kpi token creation form)
- opening a campaign card
- inside the campaign card the oracle reality frame load can fail

We need a way to display an error state to the user, something that tells him the page is currently not working.

**Comment by borisblock3007** [comment]
added this image to 'ready' :)
<img width="677" alt="Screenshot 2023-03-27 at 18 06 10" src="https://user-images.githubusercontent.com/25454493/227926043-63c21556-6c17-44b7-a22c-fb1b57846383.png">
