### ISSUE TITLE
Implement Search & filtering

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/v1-monorepo#24]
In order to implement filtering some work must be done on the backend AND frontend. This is a brief explanation of a couple ideas that must be tested and assessed.

Filtering should be done on 2 main categories of fields:

- Generic ones, that apply to all KPI tokens (these are for example status, expiration date, creator, used template, number of conditions etc etc)
- Template-specific ones. These are represented by the blob of ABI-encoded data returned by the `data` function on each KPI token template and instance, and are specific to the used template, and potentially change between each version of the template and are potentially updated block to block.

For the first category, it's relatively simple to implement filtering because we have a reliable interface to work with. We know that all KPI tokens can be filtered with some params regardless of template, and that makes our life easier. Additionally, it's also simpler because this kind of data is static, and in 99.9% of the cases, it won't change once the KPI token is created and put on chain. That makes it possible to fetch this data once and apply filters on it forever after "in the session".

The second category is trickier and I think we have to tackle the problem from frontend and backend perspectives separately.

## Frontend

The first thing we'll have to define (and that to be honest applies to both frontend and backend) is how the platform determines which attributes a campaign using a certain template has/is filterable on. To do this, a key must be added to each template descriptor with the following structure:

```
...
"attributes": [
    {
        "name": "Attribute",
        "type": "erc20-token-amount",
        "solidityType": "tuple(address token,uint256 amount)"
    },
    ...
]
...
```

This is relatively similar to how an NFT specifies metadata.

The `attributes` array should give the frontend a generalized way to display filters that map to what the template returns in the `data` function. `data` returns ABI-encoded generic data which is specific to each template's implementation, and each template can have a completely different data structure and decoding procedure. This extra key in the template descriptor JSON should "teach" the frontend how to decode data results so that it can display appropriate filters to the user and apply them on the returned `data` from the KPI token. An example of how this could be done:

Let's pretend we have a KPI token instantiated with a template with the following attributes in the descriptor:

```json
[
    {
        "id": "collaterals"
        "label": "Collaterals",
        "filterType": "erc20-token-amounts",
        "solidityType": "tuple(address token,uint256 amount)[]"
    }
]
```

And with the contract looking something like this:

```solidity
struct TokenAmount {
    address token;
    uint256 amount;
}

...
TokenAmount[] internal collaterals;
...

...
function data() external override returns(bytes memory) {
    // let's assume `collaterals` has one element with amount 1 
    // and token 0x0000000000000000000000000000000000000002
    return abi.encode(collaterals);
}
...
```

Now the code to decode the template data would be something like this in the frontend (using the current version of the SDK):

```js
const kpiTokenAddress = "0x0000000000000000000000000000000000000001";
const kpiToken = await Fetcher.fetchKpiTokens(provider, kpiTokenAddress);
const { template: { specification: { attributes } }, rawData } = kpiToken;

// use ethers
const decoded = defaultAbiCoder.decode(attributes.map(attribute => attribute.solidityType), rawData);

// `decoded` now should have the following structure: [{ token: "0x0000000000000000000000000000000000000002", amount: "1" }]

// in order to make order not count, let's turn this into a map indexed by the attribute id
const filterable = attributes.reduce((accumulator, attribute, i) => {
    accumulator[attribute.id] = decoded[i];
}, {})
```

We now should be able to apply filters on the `filterable` structure and display filters on the UI through the `filterType` key in the attribute element (these should be enumerated and the frontend must support each one of them). Keep in mind that this logic could be applied directly in the SDK to make it transparent to the caller. Initial filtering widget types could be:

- Number
- ERC20 token amount
- Select
- ...

The user is able to interact with these to specify filters he wants to apply (we could look at NFT marketplaces to define the UX for them).

## Backend implementation

Once the user is shown the filters, we actually have to filer right? We need to check this out under 2 different perspectives, since in my mind the user should have the option to go in decentralization mode with Carrot. It should be a setting on the dapp, and in this sense we already have some progress, with a service worker running an in-browser IPFS node and with the planned possibility to specify custom RPC urls and stuff.

Having said this, with filtering for template-specific data it becomes tough to give the same user experience in decentralization mode if we want to support rich filtering. The main issue is that I can envision templates where collaterals or other data updates block to block, and users generally speaking want to filter on the most recent data. This would translate to fetching up to date data for each KPI token created on the platform (at least for currently active campaigns, since we can assume no changes will happen on expired or resolved campaigns' data) each time a user wants to apply filters. It's easy to see this is not exactly the most scalable approach if a considerable number of campaigns are active at the same time.

For decentralization only mode there are a couple choices/optimizations to make:

- We can decide to do the data fetch calls only once each time the user gets on the filtering page (unless cached data is fresh, for example if the user returns on the filtering page more times in a short amount of time). This will still potentially take a considerable amount of time if many campaigns are created on the platform.
- We can decide to have a sort of compromise and only do the calls every x blocks.
- We can ditch rich filtering altogether in decentralization mode.
- We can have a mixed approach where rich filtering is available in decentralization mode only up to x active campaigns, and gets disabled otherwise (potentially, we can have an option to override this behavior to the user if he wants to go full decentralization maxi and wait a potentially long time for filters to be applied).

Before choosing an option, we'll need to do some testing with a variable number of active campaigns, to see which one is viable and to see which isn't. As of now to be honest I think disabling rich filtering in decentralization mode is the way to go since even if not many campaigns are active at the time when the user wants to filter, we still have to fetch the static data mentioned above for all the campaigns if no cache is already in the user's machine, making this whole thing hard to do.

For "normal", non decentralization mode there are a couple of ways to implement this too. The issue of always working on the freshest data still applies, but it's easier to tackle since it can be done in a quicker way in the backend. I see 2 main ways to go about this:

- Using a Subgraph
- implementing a custom solution

A possible subgraph implementation would easily keep track of both currently active and expired campaigns and react to onchain events. Since we've said that for active campaigns we can have block-to-block-updates though, having a block handler that fetches up to date data from the instance at each block could be the way to go. I'm a bit worried on this because if the active campaigns are many, a lot of calls would have to be performed each time and I'm not sure TheGraph supports multicall, which could lead us to a situation where potentially the updates take so long that the subgraph starts to lag.

With a custom solution the approach is basically the same with a block handler, but calls could be batched in order to optimize the IO time.

Another approach altogether, that applies to both decentralization and non-decentralization modes, would be to require for each template to specify if it requires per-block updates or not. All the logic above applies, but it would be applied to a potentially small subset of all instances.

**Comment by Diogomartf** [comment]
this issue is related to #153

**Comment by Diogomartf** [comment]
related to #172 #173 #174 issues.
