### ISSUE TITLE
Green color on the button and on the "holding" tag on the card competing for attention

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/v1-monorepo#89]
I think the green with active button might be competing with "holding" tag on the card. People also can associate the green for clicking. I would suggest explore an alternative and see if it's better.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/5664434/216721269-730ff856-46d4-4ea6-9411-047899a0ca0f.png">

**Comment by luzzif** [comment]
The holding tag might be left off for the v1 and for the foreseeable future, closing this
