### ISSUE TITLE
The main title should be aligned with the logo

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/v1-monorepo#90]
We currently have this spacing left problem with the campaigns with filters section and the current nav bar at the top.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/5664434/216721958-10d446a6-9706-477f-b992-ea76fe051af8.png">

The main title should be aligned with the logo.

**Correct alignment in the landing page**
<img width="371" alt="image" src="https://user-images.githubusercontent.com/5664434/216721863-59cc50a8-3e4d-461b-b10b-ffd5fbdb71a7.png">

The problem here is that we need more width for the campaigns with filters section.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/5664434/216722367-1a6c6108-e455-4ed8-b43f-8fc378ac7249.png">
(cards not displaying correctly yet)

**Comment by luzzif** [comment]
@borisblock3007 ???

**Comment by borisblock3007** [comment]
if we widen the navbar throughout the whole dapp it should look fine, i discussed the issue with Dirk and he agreed :)
