### ISSUE TITLE
[campaigns] Fix alignment title and cards.

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/v1-monorepo#91]
The cards are not aligned with the title/filters.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/5664434/216723708-d9a7e350-a527-4e5c-9705-ce6223ab38e4.png">

**Comment by luzzif** [comment]
Closing as related (and partially a duplicate) of https://github.com/carrot-kpi/v1-monorepo/issues/90
